# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI for devops challenge

on:
  pull_request:
    types: [opened, synchronize ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
    - uses: actions/checkout@v3
    - name: Run clean install
      run: npm ci
    - name: Run Linter
      run: npm run lint
    - name: Install Prettier
      run: npm i -g prettier
    - name: Install react-scripts
      run: npm i react-scripts@latest
    - name: Run Prettier
      run: npm run prettier
    - name: Run Tests
      run: npm run test
    - name: Run Build
      run: npm run build
